### ISSUE TITLE
Dependabot posts expired/old links

### ISSUE THREAD

**Issue by SparrowBrain** [SparrowBrain/gerald-the-discord-bot#462]
Sometimes a huge list of expired links are posted

Could be connection to s3 bucket issue and poor handling.
Could be something else.

```
Sep 23 11:07:46 ip-10-0-0-166 web: Got response: 200
Sep 23 11:07:46 ip-10-0-0-166 web: [
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-minion-masters-mordars-malediction/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-weekend-desperados-iii-hearts-of-iron-iv-and-retimed/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-1-shortcut-kit-ultimate-bundle/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-call-of-duty-vanguard-beta/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-titan-quest-anniversary-edition-and-jagged-alliance-gold-edition/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/the-escapists-is-revealed-as-next-free-game-from-epic-games-store/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-speed-brawl-and-tharsis/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-age-of-empires-iv-beta/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-week-stellaris-09-2021/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-4-naval-strike-and-battlefield-1-turning-tides-dlc/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-weekend-madden-nfl-22-f1-2021-and-rainbow-six-siege/',
Sep 23 11:07:46 ip-10-0-0-166 web: 'https://gg.deals/freebie/speed-brawl-and-tharsis-are-revealed-as-next-free-games-from-epic-games-store/'
Sep 23 11:07:46 ip-10-0-0-166 web: ]
Sep 23 12:05:48 ip-10-0-0-166 web: > gerald-the-discord-bot@1.0.0 start /var/app/current
Sep 23 12:05:48 ip-10-0-0-166 web: > node ./dist/index.js
Sep 23 12:05:49 ip-10-0-0-166 web: Got response: 200
Sep 23 12:05:49 ip-10-0-0-166 web: [
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-minion-masters-mordars-malediction/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-weekend-desperados-iii-hearts-of-iron-iv-and-retimed/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-1-shortcut-kit-ultimate-bundle/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-call-of-duty-vanguard-beta/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-titan-quest-anniversary-edition-and-jagged-alliance-gold-edition/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/the-escapists-is-revealed-as-next-free-game-from-epic-games-store/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-speed-brawl-and-tharsis/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-age-of-empires-iv-beta/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-week-stellaris-09-2021/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-4-naval-strike-and-battlefield-1-turning-tides-dlc/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-weekend-madden-nfl-22-f1-2021-and-rainbow-six-siege/',
Sep 23 12:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/speed-brawl-and-tharsis-are-revealed-as-next-free-games-from-epic-games-store/'
Sep 23 12:05:49 ip-10-0-0-166 web: ]
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-minion-masters-mordars-malediction/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-weekend-desperados-iii-hearts-of-iron-iv-and-retimed/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-battlefield-1-shortcut-kit-ultimate-bundle/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-call-of-duty-vanguard-beta/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-titan-quest-anniversary-edition-and-jagged-alliance-gold-edition/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/the-escapists-is-revealed-as-next-free-game-from-epic-games-store/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-speed-brawl-and-tharsis/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-age-of-empires-iv-beta/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-week-stellaris-09-2021/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-battlefield-4-naval-strike-and-battlefield-1-turning-tides-dlc/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-weekend-madden-nfl-22-f1-2021-and-rainbow-six-siege/
Sep 23 12:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/speed-brawl-and-tharsis-are-revealed-as-next-free-games-from-epic-games-store/
Sep 23 12:05:49 ip-10-0-0-166 web: Ready!
Sep 23 12:05:49 ip-10-0-0-166 web: loading subs from s3
Sep 23 12:05:49 ip-10-0-0-166 web: loaded channel ids: xxxxxxx
Sep 23 12:05:49 ip-10-0-0-166 web: DiscordAPIError: Unknown Channel
Sep 23 12:05:49 ip-10-0-0-166 web: at RequestHandler.execute (/var/app/current/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
Sep 23 12:05:49 ip-10-0-0-166 web: at processTicksAndRejections (internal/process/task_queues.js:97:5)
Sep 23 12:05:49 ip-10-0-0-166 web: at async RequestHandler.push (/var/app/current/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
Sep 23 12:05:49 ip-10-0-0-166 web: at async ChannelManager.fetch (/var/app/current/node_modules/discord.js/src/managers/ChannelManager.js:91:18) {
Sep 23 12:05:49 ip-10-0-0-166 web: method: 'get',
Sep 23 12:05:49 ip-10-0-0-166 web: path: '/channels/xxxx',
Sep 23 12:05:49 ip-10-0-0-166 web: code: 10003,
Sep 23 12:05:49 ip-10-0-0-166 web: httpStatus: 404
Sep 23 12:05:49 ip-10-0-0-166 web: }
Sep 23 12:05:49 ip-10-0-0-166 web: Error while fetching channel xxx.
Sep 23 12:05:49 ip-10-0-0-166 web: subscription added to xxx
Sep 23 12:05:49 ip-10-0-0-166 web: subscription added to xxx
Sep 23 12:05:49 ip-10-0-0-166 web: subscription added to xxx
Sep 23 13:05:49 ip-10-0-0-166 web: Got response: 200
Sep 23 13:05:49 ip-10-0-0-166 web: [
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-minion-masters-mordars-malediction/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-weekend-desperados-iii-hearts-of-iron-iv-and-retimed/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-1-shortcut-kit-ultimate-bundle/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-call-of-duty-vanguard-beta/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-titan-quest-anniversary-edition-and-jagged-alliance-gold-edition/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/the-escapists-is-revealed-as-next-free-game-from-epic-games-store/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-speed-brawl-and-tharsis/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-age-of-empires-iv-beta/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-week-stellaris-09-2021/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-4-naval-strike-and-battlefield-1-turning-tides-dlc/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-weekend-madden-nfl-22-f1-2021-and-rainbow-six-siege/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/speed-brawl-and-tharsis-are-revealed-as-next-free-games-from-epic-games-store/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-sheltered/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-new-world-open-beta/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-random-steam-key-for-dead-by-daylight-full-game-or-chapter-expansions/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-surviving-mars-on-steam/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-assassins-creed-valhalla-odins-blessing-tattoo-set/',
Sep 23 13:05:49 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-trials-fusion/'
Sep 23 13:05:49 ip-10-0-0-166 web: ]
Sep 23 13:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-sheltered/
Sep 23 13:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-new-world-open-beta/
Sep 23 13:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-random-steam-key-for-dead-by-daylight-full-game-or-chapter-expansions/
Sep 23 13:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-surviving-mars-on-steam/
Sep 23 13:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-assassins-creed-valhalla-odins-blessing-tattoo-set/
Sep 23 13:05:49 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-trials-fusion/
```

**Comment by SparrowBrain** [comment]
Issue happened, since gg.deals changed the layout and lists 18 items instead of 12.

Suggestion: limit the amount of items that can generate new deals, or limit that only top of the list can generate new deals.

**Comment by SparrowBrain** [comment]
Another instance of it happening:

```
Sep 30 02:46:31 ip-10-0-0-166 web: > gerald-the-discord-bot@1.0.0 start /var/app/current
Sep 30 02:46:31 ip-10-0-0-166 web: > node ./dist/index.js
Sep 30 02:46:32 ip-10-0-0-166 web: Ready!
Sep 30 02:46:32 ip-10-0-0-166 web: loading subs from s3
Sep 30 02:46:32 ip-10-0-0-166 web: loaded channel ids: xxx
Sep 30 02:46:32 ip-10-0-0-166 web: DiscordAPIError: Unknown Channel
Sep 30 02:46:32 ip-10-0-0-166 web: at RequestHandler.execute (/var/app/current/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
Sep 30 02:46:32 ip-10-0-0-166 web: at processTicksAndRejections (internal/process/task_queues.js:97:5)
Sep 30 02:46:32 ip-10-0-0-166 web: at async RequestHandler.push (/var/app/current/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
Sep 30 02:46:32 ip-10-0-0-166 web: at async ChannelManager.fetch (/var/app/current/node_modules/discord.js/src/managers/ChannelManager.js:91:18) {
Sep 30 02:46:32 ip-10-0-0-166 web: method: 'get',
Sep 30 02:46:32 ip-10-0-0-166 web: path: '/channels/xxx',
Sep 30 02:46:32 ip-10-0-0-166 web: code: 10003,
Sep 30 02:46:32 ip-10-0-0-166 web: httpStatus: 404
Sep 30 02:46:32 ip-10-0-0-166 web: }
Sep 30 02:46:32 ip-10-0-0-166 web: Error while fetching channel xxx.
Sep 30 02:46:32 ip-10-0-0-166 web: subscription added to xxx
Sep 30 02:46:32 ip-10-0-0-166 web: subscription added to xxx
Sep 30 02:46:32 ip-10-0-0-166 web: subscription added to xxx
Sep 30 02:46:33 ip-10-0-0-166 web: Got response: 200
Sep 30 02:46:34 ip-10-0-0-166 web: [
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-1-apocalypse-and-battlefield-4-dragons-teeth/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/play-colorado-location-in-hitman-3-for-free/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-halo-infinite-beta/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/the-surge-free-with-any-purchase-on-focus-entertainment-store/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-2064-read-only-memories/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-syberia-1-2/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-banana-hell/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-questing-coupon-for-the-lord-of-the-rings-online/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-4-soldier-shortcut-bundle/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/europa-universalis-iv-is-going-to-be-next-freebie-from-epic-games-store/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-the-escapists/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-minion-masters-mordars-malediction/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-weekend-desperados-iii-hearts-of-iron-iv-and-retimed/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-battlefield-1-shortcut-kit-ultimate-bundle/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-call-of-duty-vanguard-beta/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-titan-quest-anniversary-edition-and-jagged-alliance-gold-edition/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/the-escapists-is-revealed-as-next-free-game-from-epic-games-store/',
Sep 30 02:46:34 ip-10-0-0-166 web: 'https://gg.deals/freebie/free-speed-brawl-and-tharsis/'
Sep 30 02:46:34 ip-10-0-0-166 web: ]
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-battlefield-1-apocalypse-and-battlefield-4-dragons-teeth/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/play-colorado-location-in-hitman-3-for-free/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-halo-infinite-beta/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/the-surge-free-with-any-purchase-on-focus-entertainment-store/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-2064-read-only-memories/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-syberia-1-2/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-banana-hell/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-questing-coupon-for-the-lord-of-the-rings-online/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-battlefield-4-soldier-shortcut-bundle/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/europa-universalis-iv-is-going-to-be-next-freebie-from-epic-games-store/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-the-escapists/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-minion-masters-mordars-malediction/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-weekend-desperados-iii-hearts-of-iron-iv-and-retimed/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-battlefield-1-shortcut-kit-ultimate-bundle/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-call-of-duty-vanguard-beta/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-titan-quest-anniversary-edition-and-jagged-alliance-gold-edition/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/the-escapists-is-revealed-as-next-free-game-from-epic-games-store/
Sep 30 02:46:34 ip-10-0-0-166 web: new link found: https://gg.deals/freebie/free-speed-brawl-and-tharsis/
```

**Comment by SparrowBrain** [comment]
> Another instance of it happening:
> 
> ```
> Sep 30 02:46:31 ip-10-0-0-166 web: > gerald-the-discord-bot@1.0.0 start /var/app/current
> ...
> ```

Should be fixed now

**Comment by SparrowBrain** [comment]
Happened again. Looks like aws reboots beanstalk on a whim. Added two additional fixes:
* Subscribing to new-link-found events only after the first fetch. This solves a potential race condition. Thus we safely memorize without an ability to publish
* Added an additional maxNewLinks check in memory. If the limit is exceeded, the publishing is supressed and debug channels are notified.

Should be fixed for good.
https://github.com/SparrowBrain/gerald-the-discord-bot/commit/0c1ad978e7cd01a3f6338ec08b14073dd8c5e987
